namespace Reqnroll.Helpers.Tests
{
    [TestFixture]
    public class DataTableExtensionsFactoryTests
    {
        #region Test Models with Constructor Parameters

        public class PersonWithConstructor
        {
            public PersonWithConstructor(string companyName)
            {
                CompanyName = companyName;
            }

            public string FirstName { get; set; } = string.Empty;
            public string LastName { get; set; } = string.Empty;
            public int Age { get; set; }
            public string CompanyName { get; }
        }

        public class ReadOnlyPersonWithConstructor
        {
            public ReadOnlyPersonWithConstructor(string country)
            {
                Country = country;
                CreatedAt = DateTime.UtcNow;
            }

            public string FirstName { get; init; } = string.Empty;
            public string LastName { get; init; } = string.Empty;
            public int Age { get; init; }
            public string Country { get; }
            public DateTime CreatedAt { get; }
        }

        public class OrderWithId
        {
            private static int _counter = 0;

            public OrderWithId()
            {
                OrderId = $"ORD-{++_counter:D5}";
            }

            public string OrderId { get; }
            public string CustomerName { get; set; } = string.Empty;
            public decimal TotalAmount { get; set; }
        }

        #endregion

        #region CreateSetWithReadOnlySupport with Factory Tests

        [Test]
        public void CreateSetWithFactory_WithConstructorParameter_CreatesObjectsWithFactoryValue()
        {
            // Arrange
            var table = new DataTable("FirstName", "LastName", "Age");
            table.AddRow("John", "Doe", "30");
            table.AddRow("Jane", "Smith", "25");

            // Act
            var result = table.CreateSetWithReadOnlySupport(() => new PersonWithConstructor("Acme Corp"));

            // Assert
            Assert.That(result, Has.Count.EqualTo(2));

            Assert.That(result[0].FirstName, Is.EqualTo("John"));
            Assert.That(result[0].LastName, Is.EqualTo("Doe"));
            Assert.That(result[0].Age, Is.EqualTo(30));
            Assert.That(result[0].CompanyName, Is.EqualTo("Acme Corp"));

            Assert.That(result[1].FirstName, Is.EqualTo("Jane"));
            Assert.That(result[1].LastName, Is.EqualTo("Smith"));
            Assert.That(result[1].Age, Is.EqualTo(25));
            Assert.That(result[1].CompanyName, Is.EqualTo("Acme Corp"));
        }

        [Test]
        public void CreateSetWithFactory_WithReadOnlyProperties_SetsValuesCorrectly()
        {
            // Arrange
            var table = new DataTable("FirstName", "LastName", "Age");
            table.AddRow("Alice", "Johnson", "28");
            table.AddRow("Bob", "Williams", "35");

            var testStartTime = DateTime.UtcNow;

            // Act
            var result = table.CreateSetWithReadOnlySupport(() => new ReadOnlyPersonWithConstructor("USA"));

            // Assert
            Assert.That(result, Has.Count.EqualTo(2));

            Assert.That(result[0].FirstName, Is.EqualTo("Alice"));
            Assert.That(result[0].LastName, Is.EqualTo("Johnson"));
            Assert.That(result[0].Age, Is.EqualTo(28));
            Assert.That(result[0].Country, Is.EqualTo("USA"));
            Assert.That(result[0].CreatedAt, Is.GreaterThanOrEqualTo(testStartTime));

            Assert.That(result[1].FirstName, Is.EqualTo("Bob"));
            Assert.That(result[1].LastName, Is.EqualTo("Williams"));
            Assert.That(result[1].Age, Is.EqualTo(35));
            Assert.That(result[1].Country, Is.EqualTo("USA"));
            Assert.That(result[1].CreatedAt, Is.GreaterThanOrEqualTo(testStartTime));
        }

        [Test]
        public void CreateSetWithFactory_WithAutoGeneratedId_EachInstanceGetsUniqueId()
        {
            // Arrange
            var table = new DataTable("CustomerName", "TotalAmount");
            table.AddRow("Customer A", "100.00");
            table.AddRow("Customer B", "200.00");
            table.AddRow("Customer C", "300.00");

            // Act
            var result = table.CreateSetWithReadOnlySupport(() => new OrderWithId());

            // Assert
            Assert.That(result, Has.Count.EqualTo(3));

            // Each order should have a unique ID
            var orderIds = result.Select(o => o.OrderId).ToList();
            Assert.That(orderIds, Is.Unique);

            Assert.That(result[0].CustomerName, Is.EqualTo("Customer A"));
            Assert.That(result[0].TotalAmount, Is.EqualTo(100.00m));

            Assert.That(result[1].CustomerName, Is.EqualTo("Customer B"));
            Assert.That(result[1].TotalAmount, Is.EqualTo(200.00m));

            Assert.That(result[2].CustomerName, Is.EqualTo("Customer C"));
            Assert.That(result[2].TotalAmount, Is.EqualTo(300.00m));
        }

        [Test]
        public void CreateSetWithFactory_WithEmptyTable_ReturnsEmptyList()
        {
            // Arrange
            var table = new DataTable("FirstName", "Age");

            // Act
            var result = table.CreateSetWithReadOnlySupport(() => new PersonWithConstructor("Test Co"));

            // Assert
            Assert.That(result, Is.Empty);
        }

        [Test]
        public void CreateSetWithFactory_WithComplexInitialization_ExecutesFactoryCorrectly()
        {
            // Arrange
            var table = new DataTable("FirstName", "Age");
            table.AddRow("Charlie", "40");

            var factoryCallCount = 0;

            // Act
            var result = table.CreateSetWithReadOnlySupport(() =>
            {
                factoryCallCount++;
                return new PersonWithConstructor($"Company-{factoryCallCount}");
            });

            // Assert
            Assert.That(result, Has.Count.EqualTo(1));
            Assert.That(factoryCallCount, Is.EqualTo(1));
            Assert.That(result[0].CompanyName, Is.EqualTo("Company-1"));
        }

        #endregion

        #region CreateInstanceWithFactory - Horizontal Format Tests

        [Test]
        public void CreateInstanceWithFactory_Horizontal_WithConstructorParameter_CreatesObjectWithFactoryValue()
        {
            // Arrange
            var table = new DataTable("FirstName", "LastName", "Age");
            table.AddRow("Diana", "Prince", "32");

            // Act
            var result = table.CreateInstanceWithReadOnlySupport(() => new PersonWithConstructor("Tech Inc"));

            // Assert
            Assert.That(result.FirstName, Is.EqualTo("Diana"));
            Assert.That(result.LastName, Is.EqualTo("Prince"));
            Assert.That(result.Age, Is.EqualTo(32));
            Assert.That(result.CompanyName, Is.EqualTo("Tech Inc"));
        }

        [Test]
        public void CreateInstanceWithFactory_Horizontal_WithReadOnlyProperties_SetsValuesCorrectly()
        {
            // Arrange
            var table = new DataTable("FirstName", "LastName", "Age");
            table.AddRow("Eve", "Anderson", "27");

            var testStartTime = DateTime.UtcNow;

            // Act
            var result = table.CreateInstanceWithReadOnlySupport(() => new ReadOnlyPersonWithConstructor("Canada"));

            // Assert
            Assert.That(result.FirstName, Is.EqualTo("Eve"));
            Assert.That(result.LastName, Is.EqualTo("Anderson"));
            Assert.That(result.Age, Is.EqualTo(27));
            Assert.That(result.Country, Is.EqualTo("Canada"));
            Assert.That(result.CreatedAt, Is.GreaterThanOrEqualTo(testStartTime));
        }

        [Test]
        public void CreateInstanceWithFactory_Horizontal_WithAutoGeneratedId_GeneratesId()
        {
            // Arrange
            var table = new DataTable("CustomerName", "TotalAmount");
            table.AddRow("Test Customer", "500.00");

            // Act
            var result = table.CreateInstanceWithReadOnlySupport(() => new OrderWithId());

            // Assert
            Assert.That(result.OrderId, Is.Not.Empty);
            Assert.That(result.OrderId, Does.StartWith("ORD-"));
            Assert.That(result.CustomerName, Is.EqualTo("Test Customer"));
            Assert.That(result.TotalAmount, Is.EqualTo(500.00m));
        }

        #endregion

        #region CreateInstanceWithFactory - Vertical Format Tests

        [Test]
        public void CreateInstanceWithFactory_Vertical_WithConstructorParameter_CreatesObjectWithFactoryValue()
        {
            // Arrange
            var table = new DataTable("Property", "Value");
            table.AddRow("FirstName", "Frank");
            table.AddRow("LastName", "Miller");
            table.AddRow("Age", "45");

            // Act
            var result = table.CreateInstanceWithReadOnlySupport(() => new PersonWithConstructor("Global Corp"));

            // Assert
            Assert.That(result.FirstName, Is.EqualTo("Frank"));
            Assert.That(result.LastName, Is.EqualTo("Miller"));
            Assert.That(result.Age, Is.EqualTo(45));
            Assert.That(result.CompanyName, Is.EqualTo("Global Corp"));
        }

        [Test]
        public void CreateInstanceWithFactory_Vertical_WithReadOnlyProperties_SetsValuesCorrectly()
        {
            // Arrange
            var table = new DataTable("Property", "Value");
            table.AddRow("FirstName", "Grace");
            table.AddRow("LastName", "Hopper");
            table.AddRow("Age", "29");

            var testStartTime = DateTime.UtcNow;

            // Act
            var result = table.CreateInstanceWithReadOnlySupport(() => new ReadOnlyPersonWithConstructor("UK"));

            // Assert
            Assert.That(result.FirstName, Is.EqualTo("Grace"));
            Assert.That(result.LastName, Is.EqualTo("Hopper"));
            Assert.That(result.Age, Is.EqualTo(29));
            Assert.That(result.Country, Is.EqualTo("UK"));
            Assert.That(result.CreatedAt, Is.GreaterThanOrEqualTo(testStartTime));
        }

        [Test]
        public void CreateInstanceWithFactory_Vertical_WithAutoGeneratedId_GeneratesId()
        {
            // Arrange
            var table = new DataTable("Property", "Value");
            table.AddRow("CustomerName", "Vertical Customer");
            table.AddRow("TotalAmount", "750.50");

            // Act
            var result = table.CreateInstanceWithReadOnlySupport(() => new OrderWithId());

            // Assert
            Assert.That(result.OrderId, Is.Not.Empty);
            Assert.That(result.OrderId, Does.StartWith("ORD-"));
            Assert.That(result.CustomerName, Is.EqualTo("Vertical Customer"));
            Assert.That(result.TotalAmount, Is.EqualTo(750.50m));
        }

        [Test]
        public void CreateInstanceWithFactory_Vertical_CaseInsensitivePropertyColumn_Works()
        {
            // Arrange
            var table = new DataTable("property", "value");
            table.AddRow("FirstName", "Helen");
            table.AddRow("Age", "33");

            // Act
            var result = table.CreateInstanceWithReadOnlySupport(() => new PersonWithConstructor("Test Company"));

            // Assert
            Assert.That(result.FirstName, Is.EqualTo("Helen"));
            Assert.That(result.Age, Is.EqualTo(33));
            Assert.That(result.CompanyName, Is.EqualTo("Test Company"));
        }

        #endregion

        #region Edge Cases and Error Handling

        [Test]
        public void CreateSetWithFactory_NullFactory_ThrowsArgumentNullException()
        {
            // Arrange
            var table = new DataTable("FirstName", "Age");
            table.AddRow("Test", "30");

            // Act & Assert
            Assert.Throws<NullReferenceException>(() =>
                table.CreateSetWithReadOnlySupport<PersonWithConstructor>(null!));
        }

        [Test]
        public void CreateInstanceWithFactory_NullFactory_ThrowsArgumentNullException()
        {
            // Arrange
            var table = new DataTable("FirstName", "Age");
            table.AddRow("Test", "30");

            // Act & Assert
            Assert.Throws<NullReferenceException>(() =>
                table.CreateInstanceWithReadOnlySupport<PersonWithConstructor>(null!));
        }

        [Test]
        public void CreateSetWithFactory_FactoryThrowsException_PropagatesException()
        {
            // Arrange
            var table = new DataTable("FirstName", "Age");
            table.AddRow("Test", "30");

            // Act & Assert
            var ex = Assert.Throws<InvalidOperationException>(() =>
                table.CreateSetWithReadOnlySupport<PersonWithConstructor>(() =>
                    throw new InvalidOperationException("Factory error")));

            Assert.That(ex.Message, Is.EqualTo("Factory error"));
        }

        [Test]
        public void CreateInstanceWithFactory_FactoryThrowsException_PropagatesException()
        {
            // Arrange
            var table = new DataTable("FirstName", "Age");
            table.AddRow("Test", "30");

            // Act & Assert
            var ex = Assert.Throws<InvalidOperationException>(() =>
                table.CreateInstanceWithReadOnlySupport<PersonWithConstructor>(() =>
                    throw new InvalidOperationException("Factory error")));

            Assert.That(ex.Message, Is.EqualTo("Factory error"));
        }

        [Test]
        public void CreateSetWithFactory_WithNonExistentProperty_IgnoresColumn()
        {
            // Arrange
            var table = new DataTable("FirstName", "Age", "NonExistentProperty");
            table.AddRow("Ivan", "33", "IgnoredValue");

            // Act
            var result = table.CreateSetWithReadOnlySupport(() => new PersonWithConstructor("My Company"));

            // Assert
            Assert.That(result, Has.Count.EqualTo(1));
            Assert.That(result[0].FirstName, Is.EqualTo("Ivan"));
            Assert.That(result[0].Age, Is.EqualTo(33));
            Assert.That(result[0].CompanyName, Is.EqualTo("My Company"));
        }

        [Test]
        public void CreateInstanceWithFactory_WithPartialData_SetsOnlyProvidedProperties()
        {
            // Arrange
            var table = new DataTable("FirstName");
            table.AddRow("Jack");

            // Act
            var result = table.CreateInstanceWithReadOnlySupport(() => new PersonWithConstructor("Partial Co"));

            // Assert
            Assert.That(result.FirstName, Is.EqualTo("Jack"));
            Assert.That(result.Age, Is.EqualTo(0)); // Default value
            Assert.That(result.LastName, Is.EqualTo(string.Empty)); // Default value
            Assert.That(result.CompanyName, Is.EqualTo("Partial Co"));
        }

        #endregion
    }
}